// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using etap2;

namespace etap2.Migrations
{
    [DbContext(typeof(HistoryContext))]
    partial class HistoryContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079");

            modelBuilder.Entity("etap2.History", b =>
                {
                    b.Property<int>("HistoryId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("formula");

                    b.Property<double?>("from");

                    b.Property<int?>("n");

                    b.Property<double?>("to");

                    b.Property<double?>("x");

                    b.HasKey("HistoryId");

                    b.ToTable("Histories");
                });
#pragma warning restore 612, 618
        }
    }
}
